### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by leh103** [DerelictOrg/DerelictGLES#11]
When building DerelictGLES-master with `dub build -b release, I get errors saying that ELGint is not defined. It is defined as a alias to int in the eglplatform.d file. I may have downloaded the master a while back, so it may not be current, although the github pages indicates it has not been worked on for 2 years. Here is a screenshot of the errors:
![screenshot from 2017-01-29 13 37 31](https://cloud.githubusercontent.com/assets/13159586/22407745/b7e55f92-e629-11e6-892a-2f5f7207dac3.png)
I am using the 64-bit debian distrubition from Mint Linux (Mint Linux lmde-2) on a machine that has support for openGL 3.x.

**Comment by mdparker** [comment]
This binding has never been release ready and I just haven't been motivated to make it so. I don't use GLES and I have very little idea about how to set it up outside of ANGLE on Windows. I have 64-bit Ubuntu installed on an old laptop, so I'll try to make time in the coming days to see if I can reproduce this. If you're able to figure it out in the interim, please let me know.

**Comment by leh103** [comment]
I am not sure that I need it either. I am trying to learn and then use openGL and I wanted to use the Derelict Bindings, but I don't what to use Dub. I would like to be able to use the static debug libraries in my local build directory for a project. As indicated before all the errors have to do with not being able to find the definition of EGLint, which is in the eglplatform.d file. This file is imported by the egltypes.d file. I did notice that unlike all the other types in the types file this one doesn't have a capital after the EGL as in EGLint instead of EGLInt. Also, in the eglplatforms.d file the alias for this is the same for all the OS's could the alias be put in the egltypes.d file like the other type alias? For me the problem may actually be that I do not have the libgles.a on my system. I will have to check this out. I will keep you informed and like I said at the start I may not even need this one anyway. Thanks

**Comment by mdparker** [comment]
> I am trying to learn and then use openGL and I wanted to use the Derelict Bindings

In that case, you should be using DerelictGL3. 

> I don't what to use Dub

That may be the source of your current problem. When you build DerelictGLES, are you adding DerelictUtil to your import path?

**Comment by leh103** [comment]
1. I probably will be using DerelictGL3 and maybe other, and I will probably not be using DerelictGLES, that is not the problem see #2.

2. The error message referenced in my first post was because I was trying to build DereclictGLES using a downloaded master. As you can see from the screenshot I was using dub with your dub.json file included with the download, which does include a dependence on DerelictUtil. I have been able to build 4 out of 5 downloads masters.

3.Thanks for the information about it having no link-time dependency. I will keep that in mind when I start the project. I guess I should read the chapter on Derelict in you book which I have or atleast the Derelict documentation. Although I don't always understand it since I have always used static bindings and static libraries.

**Comment by mdparker** [comment]
> I was using dub

Sorry about that. I knew that when I wrote the first reply, but it slipped my mind by the time I wrote the second one.

I believe I've found the problem. A buggy static if condition. I had some time to kill and have my MacBook with me, so I haven't tested it on Linux yet. But I'm sure I've fixed it. If you pull the latest master, that particular error should go away. I'm not going to tag a new release yet. I want to get this package cleaned up a bit before I do that & make sure it's all up to date.

**Comment by leh103** [comment]
I was successful in building the new master on my Linux desktop machine. I will also try it on my laptop later. Thank you for your help. I am closing this issue if its OK with you.

I reread the Derelict documentation last night, so I have a better understanding of how it is used. However, I still do not know if I will be using DerelictGLES, but I am OCD enough to want to build it along with the others.
